- name: vars preference
  hosts: local
  connection: local
  vars:
    TEST: this variable is from play
  # vars_files:
  # - course.yaml
  vars_prompt:
  - name: TEST
    prompt: Enter the name of the variable
    private: false  
  tasks:
  - name: testing variables preference
    # vars:
    #   TEST: this variable is from task
    ansible.builtin.debug:
      msg: "Test: {{TEST}}"

#1. Args or commandline
#2. from task 
#3. files
#4. prompt
#5. play
#6. inventory


