- name: install packages using loops
  hosts: local
  connection: local
  tasks:
    - name: install
      ansible.builtin.package:
        ansible.builtin.debug:
          msg: "{{item}}"
        loop:
          - nginx
          - mysql
          - zip
